In [1]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('./car_sensors.csv')

df.head()

safe       S1        S2        S3   S4        S5   S6   S7  S8  S9  ...  \
0     1  36.2247  10.77330  0.243897  596  100.6710  0.0  0.0   1  28  ...   
1     1  35.7343  17.45510  0.243897  600  100.0000  0.0  0.0   1  14  ...   
2     1  31.6561   7.61366  0.308763  604   99.3377  0.0  0.0   1   4  ...   
3     1  33.8320  13.11190  0.293195  616   97.4026  0.0  0.0   1   8  ...   
4     1  42.5138  13.99850  0.259465  632   94.9367  0.0  0.0   1   8  ...   

   S13  S14  S15    S16  S17      S18  S19   S20  S21      S22  
0    1   57  0.0  0.280  240  5.99375    0   0.0    4  14.9382  
1    1   57  0.0  0.175  240  5.99375    0   0.0    4  14.8827  
2    1   58  0.0  0.280  240  5.99375    0   0.0    4  14.6005  
3    1   58  0.0  0.385  240  4.50625    0  13.0    4  14.6782  
4    1   57  0.0  0.070  240  5.99375    0  19.5    4  15.3461  

[5 rows x 23 columns]

In [4]:
df.shape

(33239, 23)

In [5]:
X = df.drop('safe', axis=1)
y = df['safe']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# sample rows --> randomly select n rows from the training set
def sample_rows(X_train, y_train, n=X_train.shape[0]):
    sample_indices = np.random.choice(X_train.index, size=n, replace=False)
    return X_train.loc[sample_indices], y_train.loc[sample_indices]


In [39]:
# randomly sample + less feature selection
# assume t is total number of rows in the training set here we only select p which is (p<t)
# p = underroot t

def sample_rows_cols(X_train, y_train, p = None, n=X_train.shape[0]):
    if p is None:
        p = int(np.sqrt(X_train.shape[0]))
    sample_indices = np.random.choice(X_train.index, size=n, replace=False)
    sample_indices_cols = np.random.choice(X_train.columns, size=p, replace=False)
    return X_train.loc[sample_indices, sample_indices_cols], y_train.loc[sample_indices]

In [ ]:


X_sample1 = sample_rows(X_train, y_train, n= X_train.shape[0])
sample_df_1 = pd.concat([X_sample1[0], X_sample1[1]], axis=1)
sample_df_1.shape
sample_df_1.head()  

S1        S2        S3    S4       S5      S6       S7  S8  S9  \
17291  32.5575  10.31440  0.085623   876  68.4932  31.470  155.824   0  10   
3857   26.7769   7.97903  0.076542  1144  52.4476   0.000    0.000   0   0   
21397  31.2283  14.64240  1.445220   732  81.9672  18.048   89.810   0  48   
28278  30.1826  13.66040  0.334710  1228  48.8599   0.010  213.990   0   0   
4352   31.2550   9.27252  0.303574  1036  57.9151   0.012    3.631   0   0   

            S10  ...  S14  S15   S16   S17       S18  S19   S20  S21  \
17291  0.015749  ...   70  0.0  0.00   767   4.50625    0  16.9    4   
3857   0.017324  ...   41  0.0 -0.28   240  10.50000    0   0.0    1   
21397  0.015875  ...   28  0.0 -0.28  1023   4.50625    1   0.8    4   
28278  0.016064  ...   67  0.0  0.00   496   9.01250    0   0.0    1   
4352   0.017072  ...   43  0.0 -0.56   240  36.00630    0   0.0    1   

            S22  safe  
17291   8.51351     0  
3857    7.77463     1  
21397  10.75640     0  
28278  14.74360     1  
4352    7.64622     1  

[5 rows x 23 columns]

In [21]:
X_sample2 = sample_rows(X_train, y_train, n= X_train.shape[0])
sample_df_2 = pd.concat([X_sample2[0], X_sample2[1]], axis=1)
sample_df_2.shape
sample_df_2.head()

S1        S2        S3    S4       S5      S6       S7  S8  S9  \
3206   31.1107  11.87500  0.107678   784  76.5306  27.447  207.739   0   8   
22812  34.4023   9.97036  0.088218   776  77.3196  29.225   74.995   0  12   
4158   32.2194  10.95740  0.256870  1020  58.8235  25.953  343.582   0 -22   
24094  31.2698  11.80680  0.099894   644  93.1677  32.231  327.272   0   4   
25820  36.8513  15.80360  0.088218   816  73.5294   0.000    0.000   0 -30   

            S10  ...  S14  S15    S16   S17      S18  S19   S20  S21  \
3206   0.014993  ...  100  0.0 -0.385   767  1.48750    0   2.6    4   
22812  0.018584  ...  100  0.0  0.070   496  3.01875    0   0.0    4   
4158   0.015812  ...   64  0.0  0.070   752  3.01875    0   0.0    4   
24094  0.016127  ...   62  0.0  0.000  1008  1.48750    0  21.9    4   
25820  0.015875  ...    0  0.0  0.175   496  5.99375    0  16.0    4   

            S22  safe  
3206    7.02942     0  
22812  16.96090     0  
4158    6.82122     1  
24094  15.87320     1  
25820   7.12290     0  

[5 rows x 23 columns]

In [23]:
X_sample3 = sample_rows(X_train, y_train, n= X_train.shape[0])
sample_df_3 = pd.concat([X_sample3[0], X_sample3[1]], axis=1)
sample_df_3.shape
sample_df_3.head()

S1        S2        S3    S4       S5      S6       S7  S8   S9  \
15038  30.0119  13.67370  0.105083   648  92.5926  30.156  345.262   0   -8   
26443  33.2879  11.04940  0.080434   880  68.1818  27.522  344.777   0    2   
17682  37.0968  10.79320  0.317844  1012  59.2885   0.000    0.000   0    0   
1253   34.4461  19.91680  0.098597   692  86.7052   0.000    0.000   0   -4   
18519  32.9498   9.98125  0.311358  1144  52.4476   9.646   77.342   0 -180   

            S10  ...  S14   S15    S16  S17        S18  S19   S20  S21  \
15038  0.016316  ...   64   0.0  0.070  255    3.01875    0  25.0    4   
26443  0.015434  ...   70   0.0  0.070  752    7.48125    0  13.9    4   
17682  0.011843  ...   69   6.4  1.645  754  290.98100    0   0.0    2   
1253   0.015938  ...   74   0.0  0.070  255    1.48750    0   9.9    4   
18519  0.008000  ...   79  33.6 -0.385  255   22.48750    1   0.0    3   

            S22  safe  
15038  15.90790     0  
26443   7.72601     0  
17682   9.69525     1  
1253    9.61044     1  
18519  13.59080     0  

[5 rows x 23 columns]

In [24]:
dt_1 = DecisionTreeClassifier()
dt_2 = DecisionTreeClassifier()
dt_3 = DecisionTreeClassifier()

In [27]:
dt_1.fit(sample_df_1.drop('safe', axis=1), sample_df_1['safe'])

DecisionTreeClassifier()

In [28]:
dt_2.fit(sample_df_2.drop('safe', axis=1), sample_df_2['safe'])

DecisionTreeClassifier()

In [29]:
dt_3.fit(sample_df_3.drop('safe', axis=1), sample_df_3['safe'])

DecisionTreeClassifier()

In [30]:
# testing all 3 models
y_pred_1 = dt_1.predict(X_test)
y_pred_2 = dt_2.predict(X_test)
y_pred_3 = dt_3.predict(X_test)
accuracy_1 = accuracy_score(y_test, y_pred_1)
accuracy_2 = accuracy_score(y_test, y_pred_2)
accuracy_3 = accuracy_score(y_test, y_pred_3)

print(f"Accuracy of Decision Tree 1: {accuracy_1}")
print(f"Accuracy of Decision Tree 2: {accuracy_2}")
print(f"Accuracy of Decision Tree 3: {accuracy_3}")

Accuracy of Decision Tree 1: 0.9422382671480144
Accuracy of Decision Tree 2: 0.9383273164861613
Accuracy of Decision Tree 3: 0.9389290012033694


In [31]:
dt_1.predict(np.array([31.3943,15.1829,0.114165,688,87.2093,7.881,191.598,0,0,0.018773,360,0,1,80,0,-2.03,255,37.4937,1,26.3,3,16.1097]).reshape(1, -1))

c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [32]:
dt_2.predict(np.array([31.3943,15.1829,0.114165,688,87.2093,7.881,191.598,0,0,0.018773,360,0,1,80,0,-2.03,255,37.4937,1,26.3,3,16.1097]).reshape(1, -1))

c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [33]:
dt_3.predict(np.array([31.3943,15.1829,0.114165,688,87.2093,7.881,191.598,0,0,0.018773,360,0,1,80,0,-2.03,255,37.4937,1,26.3,3,16.1097]).reshape(1, -1))

c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [34]:
dt_1.predict(np.array([34.292,16.4897,0.298385,660,90.9091,0,0,1,0,0.016946,322,3,0,100,0,0.28,240,4.50625,0,9.1,4,14.9719]).reshape(1,-1))

c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [35]:
dt_2.predict(np.array([34.292,16.4897,0.298385,660,90.9091,0,0,1,0,0.016946,322,3,0,100,0,0.28,240,4.50625,0,9.1,4,14.9719]).reshape(1,-1))

c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [36]:
dt_3.predict(np.array([34.292,16.4897,0.298385,660,90.9091,0,0,1,0,0.016946,322,3,0,100,0,0.28,240,4.50625,0,9.1,4,14.9719]).reshape(1,-1))

c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)