In [6]:
import numpy as np

In [7]:
#neuroon with 3 inputs, weights and bias
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = (inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias)
print(output)

2.3


In [8]:
#neuroon with 4 inputs, weights and bias
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
output = (inputs[0]*weights[0] +
 inputs[1]*weights[1] +
 inputs[2]*weights[2] +
 inputs[3]*weights[3] + bias)

print(output)

4.8


In [9]:
# layer of neurons 4 input nodes ---> 3 neurons
inputs = [1.0, 2.0, 3.0, 2.5]   # ---> 1x4
weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]]  # ---> 3x4
biases = [2.0, 3.0, 0.5]
z1 = np.dot(weights,inputs) + biases
A1 = 1/(1+np.exp(-z1))  #sigmoid activation function
print(A1)    # adding the non-linearity
# print(z1)

[0.99183743 0.77029895 0.9156763 ]


In [10]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2,0.5,-0.26],
           [0.8,-0.91,-0.27],
           [-0.5,0.26,0.17],
           [1.0,-0.5,0.87]]
biases = [2.0,3.0,0.5]
z1 = np.dot(inputs,weights) + biases
A1 = 1/(1+np.exp(-z1))  #sigmoid activation function
print(A1)    # adding the non-linearity
print(z1)

[0.99183743 0.77029895 0.9156763 ]
[4.8   1.21  2.385]


In [11]:
#batch of inputs
inputs = np.array([[1.0, 2.0, 3.0, 2.5],
                   [2.0, 5.0, -1.0, 2.0],
                   [-1.5, 2.7, 3.3, -0.8]])  # ---> 3x4
weights = np.array([[0.2, 0.8, -0.5, 1.0], 
                    [0.5, -0.91, 0.26, -0.5], 
                    [-0.26, -0.27, 0.17, 0.87]])  # ---> 3x4
biases = np.array([2.0, 3.0, 0.5])
z1 = np.dot(inputs, weights.T) + biases
print(z1.shape)
print(z1)



(3, 3)
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [12]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# Output of current layer
layer_outputs = []

# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
 # Zeroed output of given neuron
 neuron_output = 0
 # For each input and weight to the neuron
 for n_input, weight in zip(inputs, neuron_weights):
 # Multiply this input by associated weight
 # and add to the neuron's output variable
#    neuron_output += n_input*weight ## W31*X1 + W32*X2 + W33*X3 + W34*X4
#    # Add bias
#  neuron_output += neuron_bias ## ## W31*X1 + W32*X2 + W33*X3 + W34*X4 + B3
    neuron_output = (n_input*weight + neuron_bias)
 # Put neuron's result to the layer's output list
 layer_outputs.append(neuron_output)
print(layer_outputs)

[4.5, 1.75, 2.675]


In [13]:
a = [1,2,3]
b = [4,5,6]
c = np.dot(a,b)
d = np.dot(b,a)
print(d)
print(c)


32
32


In [14]:
a = [1,2,3]
b=[[4,5,6],[7,8,9],[10,11,12]]
c = np.dot(a,b)
d = np.dot(b,a)
print(d)
print(c)


[32 50 68]
[48 54 60]


In [15]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,2,3],[4,5,6],[7,8,9]]
c = np.dot(a,b)
print(c)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [16]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]

bias = 2.0
z1 = np.dot(weights, inputs) + bias

print(z1)

4.8


In [25]:
def ReLu(x):
    return np.maximum(0,x)

def linear_activation(x):
    return x

In [ ]:
inputs_X  = [1.0, 2.0, 3.0, 2.5]
weights1 = [[0.2,0.5,-0.26],
           [0.8,-0.91,-0.27],
           [-0.5,0.26,0.17],
           [1.0,-0.5,0.87]]
biases1 = [2.0,3.0,0.5]
z1 = np.dot(inputs_X,weights1) + biases1
a1 = ReLu(z1)
print(a1)

[4.8   1.21  2.385]


In [ ]:
weights2 = [[2.3,0.1,-0.26],
           [0.8,-0.988,-0.27],
           [-0.5,0.26,0.3]]
biases2 = [0.5,-1.0,2.0]
z2 = np.dot(a1,weights2) + biases2
a2 = ReLu(z2)
print(a2)

3
[11.3155  0.      1.1408]


In [29]:
weights3 = [0.45,-0.994,0.87]
biases3 = 1.0
z3 = np.dot(a2,weights3) + biases3
a3 = linear_activation(z3)
print(a3)


7.084471000000001
