In [8]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv('../bagging/kc_house_data.csv')
df.head()

id             date    price  bedrooms  bathrooms  sqft_living  \
0  6762700020  20141013T000000  7700000         6       8.00        12050   
1  9808700762  20140611T000000  7062500         5       4.50        10040   
2  9208900037  20140919T000000  6885000         6       7.75         9890   
3  2470100110  20140804T000000  5570000         5       5.75         9200   
4  8907500070  20150413T000000  5350000         5       5.00         8000   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0     27600     2.5           0     3  ...     13        8570           3480   
1     37325     2.0           1     2  ...     11        7680           2360   
2     31374     2.0           0     4  ...     13        8860           1030   
3     35069     2.0           0     0  ...     13        6200           3000   
4     23985     2.0           0     4  ...     12        6720           1280   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1910          1987    98102  47.6298 -122.323           3940   
1      1940          2001    98004  47.6500 -122.214           3930   
2      2001             0    98039  47.6305 -122.240           4540   
3      2001             0    98039  47.6289 -122.233           3560   
4      2009             0    98004  47.6232 -122.220           4600   

   sqft_lot15  
0        8800  
1       25449  
2       42730  
3       24345  
4       21750  

[5 rows x 21 columns]

In [16]:
df.shape

(21613, 16)

In [4]:
cols_to_drop = ['id', 'date', 'zipcode', 'lat', 'long']
df.drop(columns=cols_to_drop, inplace=True)


In [9]:
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'sqft_living15',
       'sqft_lot15'],
      dtype='object')

In [10]:
X = df.drop(columns='price')
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [44]:
# max_depth = [3 , 5 , 7, 9, 20]

# for depth in max_depth:
#     high_bias_model = DecisionTreeRegressor(max_depth=depth, random_state=42)
#     high_bias_model.fit(X_train, y_train)
#     y_pred_train = high_bias_model.predict(X_train)
#     y_pred_test = high_bias_model.predict(X_test)
#     train_mse = mean_squared_error(y_train, y_pred_train)
#     test_mse = mean_squared_error(y_test, y_pred_test)

#     print(f"Train MSE of depth {depth}: {train_mse}")
#     print(f"Test MSE of depth {depth}: {test_mse}")
#     print("-" * 30)

high_bias_model = DecisionTreeRegressor(max_depth=3, random_state=42)
high_bias_model.fit(X_train, y_train)
y_pred_train = high_bias_model.predict(X_train)
y_pred_test = high_bias_model.predict(X_test)
train_mse = mean_squared_error(y_train, y_pred_train)
test_mse = mean_squared_error(y_test, y_pred_test)
print(f"Train MSE of depth 3: {train_mse}")
print(f"Test MSE of depth 3: {test_mse}")




Train MSE of depth 3: 61229982581.23587
Test MSE of depth 3: 52684148094.338974


In [45]:
actual_price = 134000
predicted_price = high_bias_model.predict(np.array([2,1.5,980,5000,2,0,0,3,7,980,0,1922,2003,1040,5000]).reshape(1, -1))

predicted_price

c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([358074.9415372])

In [46]:

# 125000
high_bias_model.predict(np.array([3,1,920,7314,1,0,0,3,6,920,0,1960,0,1010,7420]).reshape(1, -1))


c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([358074.9415372])

In [47]:
# 75000
high_bias_model.predict(np.array([1,0,670,43377,1,0,0,3,3,670,0,1966,0,98022,42882]).reshape(1, -1))

c:\Users\Acer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([358074.9415372])